### ISSUE TITLE
Problem with running Jupyter Notebook Tutorial on Rotational Diffusion:                            rm = pydiffusion.rotation.RotationMatrix(u.atoms, tetrahedron.atoms, verbose=True).run()

### ISSUE THREAD

**Issue by akvasan2** [bio-phys/pydiffusion#2]

**Comment by akvasan2** [comment]
When I try running pydifusion.rotation.RotationMatrix() in the example jupyter notebook provided, I get the following error message:
 
         if self._align_first_to_ref:
              # reset trajectory frame to start
             self._trajectory[self.start]
             self._first_rot = rotation_matrix(self._ref, self._mobile,
                                                 self._weights)
AttributeError: 'RotationMatrix' object has no attribute 'start'

Is this a problem with how I installed the pydiffusion package?  I did not alter any of the previous entries when running the notebook and I did not notice any issues with the previous cells.

**Comment by kain88-de** [comment]
This is a breaking change with the newest mdanalysis version. The code was developed against version 0.18.0

**Comment by akvasan2** [comment]
Thank you.  So, in order to use this code I should just uninstall mdanalysis and reinstall version 0.18.0, right?

**Comment by kain88-de** [comment]
I might have time for a fix on the weekend. The solution is to move the code at https://github.com/bio-phys/pydiffusion/blob/e7d73e6ccca4d3c051a5d9417ffd304b2a9be4a1/pydiffusion/rotation.py#L365-L371 into the prepare function.

**Comment by kain88-de** [comment]
downgrading mdanalysis will work. I recommend using a conda environment/virtual environment.

**Comment by kain88-de** [comment]
A short intro to environments in python can be found here. https://www.mdanalysis.org/2017/04/07/environments/

**Comment by akvasan2** [comment]
I moved the conditional statements to the prepare function and everything ran! 
Thanks so much!  
If you don't mind, I'm a bit curious why this was able to fix the problem using the latest mdanalysis package.

**Comment by kain88-de** [comment]
There has been a change in the [analysis class](https://github.com/MDAnalysis/mdanalysis/blob/da4979d2db19f0dc93fe27ecca966f5b91310482/package/MDAnalysis/analysis/base.py#L118). Before the `start`, `stop`, `step` arguments where passed to the init method. This has changed in version 0.19.0. These arguments are now passed to the run method to adjust which portion of a trajectory is analysed. This is helpful because you can reuse the same class to analzyse different parts of your trajectory

The RotationMatrix class needs to know the first frame to establish a reference orientation. Before I did this in the init method. Now I'm doing in prepare when the start frame is known.
